//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int CitaId { get; set; }
        public Nullable<int> MascotaId { get; set; }
        public System.DateTime FechaCita { get; set; }
        public System.TimeSpan HoraCita { get; set; }
        public Nullable<int> VeterinarioId { get; set; }
        public string MotivoConsulta { get; set; }
        public Nullable<int> SedeId { get; set; }
    
        public virtual Mascotas Mascotas { get; set; }
        public virtual Sedes Sedes { get; set; }
        public virtual Veterinarios Veterinarios { get; set; }
    }
}
